version: '3'
services:
  user-service:
    build:
      context: ./user
    ports:
      - "5001:5001"
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product
    ports:
      - "5002:5002"
    depends_on:
      - user-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
